### ISSUE TITLE
Macro Economic Concept Apply in Jupyter

### ISSUE THREAD

**Issue by hyunbin7303** [hyunbin7303/StockMarket_Manage#29]
# Todo

- [ ] Create Jupyter Script for CPI
- [ ] Create Jupyter Script for PPI 
- [ ] '' GDP
- [ ] Economic indicators... anything
